version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_URL=mongodb://mongo:27017/faqDB
      - REDIS_HOST=redis
    volumes:
      - .:/app
    restart: always

  mongo:
    image: mongo
    container_name: faq_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  redis:
    image: redis
    container_name: faq_redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  mongo_data:
